-- =============================================================================
-- OakTend - permanent campaign/partner attribution on public.users (0166)
-- RUN THIS AGAINST THE LIVE DATABASE (Supabase SQL editor).
-- Run it AFTER 0165 (see THE COLUMN LOCK below - this file re-creates the
-- public.users column-lock trigger function, so it must be the LAST of the
-- 016x files that touches it).
--
-- WHY. /go/<code> (src/app/go/[code]/route.ts) already logs a campaign_click
-- and drops a 30-day first-party cookie, and src/app/(auth)/
-- recordTermsAcceptance.ts already logs a campaign_signup analytics event
-- when a visitor carrying that cookie creates an account. That is enough to
-- answer "how many sign-ups did this link produce this week". It is NOT
-- enough to run a revenue share with a partner, which is what Landen's
-- addendum 5 (I1-I3) actually asks for:
--
--   * app_events is an analytics stream, pruned on a retention schedule. A
--     commission conversation six months from now cannot depend on it.
--   * the cookie is gone after 30 days, so nothing links the ACCOUNT back to
--     the partner once it lapses.
--   * "which accounts came from Curtis, and how many of them upgraded" is a
--     per-account question, and an event stream keyed on nothing but a
--     timestamp cannot answer it without a join that does not exist.
--
-- So the code is stamped on the account row, once, at sign-up, and the two
-- roll-up views at the bottom of this file are the whole reporting surface.
--
-- THE NAME: campaign_code, NOT referral_code. public.users ALREADY has two
-- referral columns from 0102 and neither of them is this:
--
--   users.referral_code  the account's OWN invite slug (UNIQUE, [A-Z2-9]{8},
--                        minted by src/lib/referralCode.ts). It identifies
--                        the INVITER, and it is generated by OakTend.
--   users.referred_by    the uuid of the user who invited this one. A
--                        user-to-user relationship.
--
-- A marketing/partner campaign is a third, unrelated thing: a short fixed
-- string from a build-time allowlist (src/lib/campaigns.ts) naming a SOURCE,
-- not a person with an account. Landen's note suggested "referral_code";
-- using that name would have collided with a UNIQUE column that means
-- something else entirely, so the column is campaign_code and the timestamp
-- beside it is campaign_recorded_at. Nothing about the user-to-user referral
-- system is touched by this file.
--
-- WHAT IS ALLOWED IN THE COLUMN. The CHECK mirrors CAMPAIGN_CODE_RE
-- (src/lib/campaigns.ts): ^[a-z0-9-]{2,32}$. That is a backstop, not the real
-- gate - the app only ever writes a code that survived lookupCampaign(), i.e.
-- one that is present in the frozen CAMPAIGN_CODES map. The CHECK exists so
-- that a hand-written UPDATE in the SQL editor, or any future writer that
-- forgets the allowlist, still cannot put free text in a column that gets
-- grouped by and pasted into a report.
--
-- FIRST CODE WINS. The app's write is
--   update users set campaign_code = $1, campaign_recorded_at = now()
--    where id = $2 and campaign_code is null
-- so a second sign-up-path call for the same account (the signup page and
-- /auth/callback both call recordTermsAcceptance) matches no row and changes
-- nothing. The "never overwritten" property lives in that WHERE clause, in
-- the database, not in a read-then-write in application code that could race
-- with itself. Same shape as the referred_by write in
-- src/app/onboarding/actions.ts.
--
-- PRIVACY. This is attribution, not personal data: the value names a
-- marketing source, is drawn from a fixed allowlist, and says nothing about
-- the person. It needs no special handling on account deletion -
-- public.users.id references auth.users ON DELETE CASCADE, so
-- admin.auth.admin.deleteUser() takes the whole row with it. src/lib/
-- privacy.ts eraseUserData does not scrub users.referred_by either, for
-- exactly the same reason, and it is unchanged by this migration.
--
-- Idempotent: IF NOT EXISTS columns and index, guarded ADD CONSTRAINT,
-- CREATE OR REPLACE for the function and the views, drop-then-create for the
-- trigger. Safe to re-run.
-- =============================================================================


-- =============================================================================
-- Part 1: the two columns
-- =============================================================================
alter table public.users
  add column if not exists campaign_code text;

alter table public.users
  add column if not exists campaign_recorded_at timestamptz;

-- ADD CONSTRAINT has no IF NOT EXISTS in PostgreSQL, so it is guarded by hand
-- rather than left to fail the whole paste on a re-run.
do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'public.users'::regclass
       and conname  = 'users_campaign_code_shape'
  ) then
    alter table public.users
      add constraint users_campaign_code_shape
      check (campaign_code is null or campaign_code ~ '^[a-z0-9-]{2,32}$');
  end if;
end
$$;

-- PARTIAL: the column is null for every account that did not arrive through a
-- /go/ link, which is the overwhelming majority of them. There is no query
-- anywhere that wants "the accounts with no campaign", so those rows have no
-- business being in the index.
create index if not exists users_campaign_code_idx
  on public.users (campaign_code)
  where campaign_code is not null;

comment on column public.users.campaign_code is
  'Permanent marketing/partner attribution: the /go/<code> campaign code this '
  'account arrived through, stamped once at sign-up by '
  'src/app/(auth)/recordTermsAcceptance.ts and never overwritten (that write '
  'is filtered on campaign_code is null). Values come from the frozen '
  'allowlist in src/lib/campaigns.ts. NOT users.referral_code (0102, this '
  'account''s own invite slug) and NOT users.referred_by (0102, the user who '
  'invited this one) - a campaign names a SOURCE, not a person. Service role '
  'only: see enforce_users_column_lock().';

comment on column public.users.campaign_recorded_at is
  'When campaign_code was stamped, i.e. the moment of sign-up. Set in the same '
  'UPDATE as campaign_code and, like it, never rewritten. This is the month '
  'public.campaign_signups_by_month groups on. Service role only.';


-- =============================================================================
-- Part 2: lock both columns against the account's own session
-- =============================================================================
-- Re-creates public.enforce_users_column_lock() (migration 0139) from its
-- LATEST body with the two new columns appended to v_locked. Everything else
-- in the function is byte-for-byte 0139's - the role check, the jsonb diff,
-- the error shape.
--
-- WHY THEY MUST BE LOCKED. "users self update" (0002) is a ROW rule with no
-- column list and Supabase's default table-level grants stand on
-- public.users, so without this trigger any signed-in account could PATCH its
-- own row through PostgREST with nothing but the anon key and its own
-- session token, and set campaign_code to whatever it liked - which is to say
-- assign itself to a partner's commission, or wipe an attribution that a
-- partner is owed money for. Both directions are money, so both columns are
-- service-role only.
--
-- ORDER MATTERS, AND HERE IS THE TRAP. CREATE OR REPLACE FUNCTION replaces the
-- body WHOLESALE. If a LATER migration adds a column to v_locked and then this
-- file is pasted after it, this file silently un-locks that column. The
-- inverse is also true: 0165 (internal accounts) is expected to add
-- `is_internal` to this same list, so 0165 MUST be pasted BEFORE 0166.
--
-- BASELINE AT THE TIME OF WRITING: 0165 does not exist in this working tree
-- yet (an internal-accounts change is in flight alongside this one), so the
-- body below is taken from 0139, the latest version that does exist. To make
-- the two compose in either order, 'is_internal' is listed defensively below:
-- the comparison runs through to_jsonb(NEW)/to_jsonb(OLD), so a column that
-- does not exist on this database reads NULL on both sides, is never
-- "changed", and never raises. Listing a column early is therefore a harmless
-- no-op that becomes a real lock the moment the column appears - whereas
-- omitting one that 0165 locked would be a silent regression.
--
-- IF YOU ADD A COLUMN TO public.users AFTER THIS FILE: add it to v_locked in
-- YOUR migration, copying the body from the most recent migration that
-- re-creates this function (grep the folder for enforce_users_column_lock).
create or replace function public.enforce_users_column_lock()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  -- Keep this in step with the table. A new counter, credit, plan flag,
  -- consent field, attribution or identity column on public.users belongs
  -- here the day it is added; anything not listed stays writable by the row's
  -- owner, which is the behaviour that existed before migration 0139.
  v_locked constant text[] := array[
    'id',
    'email',
    'created_at',
    'free_doc_reads_used',
    'free_inspection_reads_used',
    'free_quote_used_at',
    'free_plan_used_at',
    'sms_consent',
    'sms_consent_at',
    'referral_code',
    'referred_by',
    -- 0165 (internal accounts). Listed defensively - see the ORDER MATTERS
    -- note above. A no-op until the column exists.
    'is_internal',
    -- 0166 (this file). Partner/campaign attribution: an account must never
    -- be able to assign itself to, or erase itself from, a partner's
    -- commission.
    'campaign_code',
    'campaign_recorded_at'
  ];
  v_role    text;
  v_changed text[];
begin
  begin
    v_role := nullif(current_setting('request.jwt.claims', true), '')::jsonb
                ->> 'role';
  exception when others then
    v_role := null;
  end;

  if v_role = 'service_role'
     or current_user in ('service_role', 'postgres', 'supabase_admin',
                         'supabase_auth_admin')
  then
    return new;
  end if;

  -- Compared through jsonb rather than named IF branches so the list above is
  -- the single source of truth, and so a column that does not exist on this
  -- database yet reads NULL on both sides instead of failing to compile.
  -- `is distinct from` means a write that re-sends a locked column UNCHANGED
  -- is fine: only an actual change is refused, which keeps a plain profile
  -- save working even when it names more columns than it edits.
  select array_agg(t.col order by t.col)
    into v_changed
    from unnest(v_locked) as t(col)
   where to_jsonb(new) -> t.col is distinct from to_jsonb(old) -> t.col;

  if v_changed is not null then
    raise exception
      'These fields are managed by OakTend and cannot be changed from an account session: %',
      array_to_string(v_changed, ', ')
      using errcode = '42501';
  end if;

  return new;
end;
$$;

drop trigger if exists users_column_lock on public.users;
create trigger users_column_lock
  before update on public.users
  for each row execute function public.enforce_users_column_lock();

comment on function public.enforce_users_column_lock() is
  'BEFORE UPDATE guard on public.users. Raises 42501 when a locked column '
  '(paywall counters, consent record, user-to-user referral attribution, '
  'campaign/partner attribution, internal-account flag, id, email, '
  'created_at) actually changes and the caller is not the service role or a '
  'platform role. "users self update" (0002) is row-scoped with no column '
  'list, so without this a homeowner could reset their own free-AI-taste '
  'credits, or re-assign their own account to a partner''s commission, with '
  'one PATCH. Body last re-created by migration 0166.';


-- =============================================================================
-- Part 3: the two reporting views (SERVICE ROLE ONLY)
-- =============================================================================
-- These are the whole read side of the partner deal - docs/REFERRALS.md has
-- the two one-liners that get pasted into the SQL editor. They are views and
-- not an app screen on purpose: this is a monthly commission question asked
-- by one person, not a product feature, and there is no page anywhere that
-- should be able to count other people's accounts.
--
-- NOT security_invoker. Left at the default (security_invoker = false, i.e.
-- the view runs with its OWNER's privileges), which is what lets it read
-- across public.users despite the "users self select" RLS policy. That is
-- safe here ONLY because of the REVOKE below: no role that could be a
-- browser session is permitted to select from either view, so the only
-- caller that can reach them is the service role (and the SQL editor, which
-- runs as postgres). Set explicitly rather than relied on, so a future
-- database-level default cannot quietly flip it.
--
-- SPELLED OUT because Supabase's default privileges in the public schema
-- grant SELECT on new objects to anon and authenticated automatically: a
-- view created here WILL be world-readable through PostgREST unless the
-- grant is taken back. The REVOKEs below are the actual access control, not
-- decoration.

-- ---- Sign-ups per code per month -------------------------------------------
-- One row per (code, month). Counts ACCOUNTS, i.e. how many people created an
-- account while carrying that code's cookie. Month comes from
-- campaign_recorded_at, which is stamped in the same UPDATE as the code, so
-- it is the sign-up month by construction; coalesced to created_at only to
-- stay sane if a row is ever backfilled by hand with the code but no
-- timestamp.
create or replace view public.campaign_signups_by_month
with (security_invoker = false) as
  select
    u.campaign_code                                                  as campaign_code,
    date_trunc('month', coalesce(u.campaign_recorded_at, u.created_at))::date as month,
    count(*)::bigint                                                 as signups
  from public.users u
  where u.campaign_code is not null
  group by 1, 2;

revoke all on public.campaign_signups_by_month from anon, authenticated;
grant select on public.campaign_signups_by_month to service_role;

comment on view public.campaign_signups_by_month is
  'Partner/campaign reporting (0166). Accounts created per campaign code per '
  'month, from public.users.campaign_code. SERVICE ROLE ONLY - anon and '
  'authenticated are revoked explicitly, because Supabase''s default '
  'privileges would otherwise grant SELECT on it in the public schema. See '
  'docs/REFERRALS.md.';

-- ---- Upgrades per code per month -------------------------------------------
-- "Upgrade" = the attributed account holds a HOMEOWNER-side subscription row
-- that reached status 'active'. public.subscriptions (0025, re-keyed to one
-- row per (user_id, side) by 0039) is the table the Stripe webhook
-- (src/app/api/stripe/webhook/route.ts) writes; side = 'homeowner' is the
-- Plus membership, side = 'pro' is the contractor plan and is deliberately
-- excluded here - a partner referral deal is about homeowners.
--
-- 'active' ONLY, not 'trialing'. src/lib/subscription.ts draws exactly this
-- line: isLive() accepts both, but PlusTier maps 'trialing' to "live but
-- nothing has been charged yet" and 'active' to "paid". A commission is paid
-- out of money that actually moved, so this view counts 'active'.
--
-- THE MONTH IS AN APPROXIMATION, AND THIS IS THE CAVEAT TO READ. public.
-- subscriptions carries created_at (row first written, i.e. checkout) and
-- updated_at (last webhook write, which moves on every renewal, plan change
-- and cancellation). Neither one is "the moment this subscription first
-- became paid" - the table has no such column. created_at is used because it
-- is STABLE (updated_at would silently re-bucket an account into a later
-- month on its next renewal, so the same month's number would change every
-- time it was run), and because for the ordinary path - checkout, immediate
-- charge - it is right. It is early by the length of the trial for an
-- account that started on a trial and converted later. If exact
-- became-paid-at months are ever needed, that is a new column on
-- public.subscriptions written by the webhook, not a change to this view.
--
-- DISTINCT user_id: subscriptions is already unique on (user_id, side) after
-- 0039, so the count cannot double today; it is spelled out so the view
-- stays correct if that key is ever widened.
create or replace view public.campaign_upgrades_by_month
with (security_invoker = false) as
  select
    u.campaign_code                                as campaign_code,
    date_trunc('month', s.created_at)::date        as month,
    count(distinct s.user_id)::bigint              as upgrades
  from public.users u
  join public.subscriptions s
    on s.user_id = u.id
  where u.campaign_code is not null
    and s.side   = 'homeowner'
    and s.status = 'active'
  group by 1, 2;

revoke all on public.campaign_upgrades_by_month from anon, authenticated;
grant select on public.campaign_upgrades_by_month to service_role;

comment on view public.campaign_upgrades_by_month is
  'Partner/campaign reporting (0166). Attributed accounts that reached a PAID '
  'homeowner-side subscription (public.subscriptions.status = ''active'', '
  'side = ''homeowner''), bucketed by subscriptions.created_at - the table '
  'has no became-paid-at timestamp, so the month is the CHECKOUT month and is '
  'early by the trial length for an account that converted from a trial. '
  'SERVICE ROLE ONLY. See docs/REFERRALS.md.';


-- =============================================================================
-- RISK / VERIFICATION NOTES
--
-- 1. Nothing in this file backfills. Every account that signed up before it
--    was pasted has campaign_code null, including anyone who already used
--    /go/curtis. If that matters, the campaign_signup rows in app_events are
--    the only record of those, and a backfill would be a hand-written UPDATE
--    joining app_events - not part of this migration, on purpose.
--
-- 2. The app tolerates this file NOT being pasted. The campaign_code write in
--    recordTermsAcceptance.ts goes through isMissingSchemaError
--    (src/lib/dbErrors.ts): a missing column logs one warning and continues,
--    the campaign_signup analytics event still lands, and sign-up is
--    unaffected either way. So there is no deploy-order requirement between
--    the app and this migration.
--
-- 3. Verify the columns (expect two rows):
--      select column_name, data_type, is_nullable
--        from information_schema.columns
--       where table_schema = 'public' and table_name = 'users'
--         and column_name in ('campaign_code', 'campaign_recorded_at');
--
-- 4. Verify the CHECK actually refuses junk. Expect the first to raise 23514
--    and the second to succeed; both are rolled back:
--      begin;
--        update public.users set campaign_code = 'NOT A CODE'
--         where id = (select id from public.users limit 1);
--      rollback;
--      begin;
--        update public.users set campaign_code = 'curtis'
--         where id = (select id from public.users limit 1);
--      rollback;
--
-- 5. Verify the lock covers the new columns. Same borrowed-role block as
--    migration 0139's note 6, with free_doc_reads_used swapped for
--    campaign_code; expect it to be refused with 42501.
--
-- 6. THE IMPORTANT ONE - verify neither view is readable by a browser role
--    (expect ZERO rows):
--      select table_name, grantee, privilege_type
--        from information_schema.table_privileges
--       where table_schema = 'public'
--         and table_name in ('campaign_signups_by_month',
--                            'campaign_upgrades_by_month')
--         and grantee in ('anon', 'authenticated');
--
-- 7. Verify the views answer (expect zero rows until someone signs up through
--    a /go/ link, which is correct, not a failure):
--      select * from public.campaign_signups_by_month
--       where campaign_code = 'curtis' order by month;
-- =============================================================================
